language: go
go:
 - 1.8

services:
  - docker

before_install:
  - docker build -t avhost/docker-matrix-irc:$TRAVIS_BRANCH .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push avhost/docker-matrix-irc:$TRAVIS_BRANCH

notifications:
  webhooks: $AVBOT_WEBHOOK
